name: CI (Build + Test + Qodana)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and run tests
        run: mvn clean test

      - name: Qodana code analysis
        uses: JetBrains/qodana-action@v2024.2
        with:
          upload-result: true
